### PR TITLE
added annotations to the model's i created

### PR DESCRIPTION
**Pull request by austingorman**
Purpose:
Added annotations to the model's i created for documentation

How it fits in context of the project:
The handbook requires annotations

Specific Feature affected:
Departments, Orders, ProductOrders, and Employees

How to test (Be thorough!):

1. Fetch my branch

2. Look for the annotations at the top of each model listed above

3. Make sure the correct model is referenced

### CODE REVIEW

**Review by Rian501 — COMMENTED** [review]
Austin, you are using things in brackets like [key] and [Required] and such. What are those? (You can explain them to me in person if that is easier). If you do not know, please remove them.

**Comment by austingorman** [comment]
[key] specifies the unique identity for the entity
[required] indicates that the property is a required field

**Comment by Rian501** [comment]
What is the C# or .NET mechanism called? Or, Why is in included?

**Comment by austingorman** [comment]
i removed the parts i dont understand.

**Comment by Rian501** [comment]
👍

**Comment by lsrichert** [comment]
Looks good to me

**Pull request merged**
