### PR TITLE
added comments to model

### PR DESCRIPTION
**Pull request by JewelRam**
Purpose:
To show who worked on what and what its for

How it fits in context of the project:
needed to comment it because we were told to

Specific Feature affected:
employeecomputers

How to test (Be thorough!):

1.open and look with your eyes to see the comments

2.

3.

### CODE REVIEW

**Review by Rian501 — COMMENTED** [review]
Jewel, you are using bracket things like  [DataType(DataType.Date)], [Required], [Key], etc. Please explain what these mean. Or, take them out.

**Comment by JewelRam** [comment]
[DataType(DataType.Date)] sets the datatype to date and allows us to use the date format dd/MM/yyyy. [Required] This means it is a required field that cannot be ignored or left out. 
[Key] shows us what the primary "key" is aka: Id.

**Comment by AmandaM04** [comment]
removed annotations in her jr-controller branch. I am able to see that her issues were fixed and conflict was resolved. GOOD TO GO

**Review by Rian501 — APPROVED** [review]
looks good to me

**Comment by austingorman** [comment]
Everything except delete works for me

**Pull request merged**
