### PR TITLE
edit the name of the controller to plural

### PR DESCRIPTION
**Pull request by AmandaM04**
Purpose: to change the name of the controller to plural and the class name to plural

How it fits in context of the project:  it keeps all of the names within the same order. Fixed the errors of saying no namespace

Specific Feature affected:

How to test (Be thorough!):

1. checkout to my branch of am-Controllers

2. open the sln file within vs

3. press IIS Express play button at the top. 

4. also cd in the folder within powershell and do the dotnet run

Note: you will get a connection error but the build should work fine. Please see!

### CODE REVIEW

**Comment by JewelRam** [comment]
woo looks good

**Comment by austingorman** [comment]
its listening

**Comment by lsrichert** [comment]
The build worked fine when I did a dotnet run in Powershell. Looks good

**Review by JewelRam — APPROVED** [review]

**Comment by BShearin99** [comment]
Everything works!

**Pull request merged**
